version: '3'
services: 
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
    ports:
      - '3306:3306'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes: 
      - /app/node_modules
      - '.:/app'
    ports:
      - '5000:5000'
    depends_on: 
      - db
    links:
      - db