apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: server
build:
  artifacts:
  - image: mhdns/lions-den-api
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - k8s/ingress-service.yaml
    - k8s/mariadb-cluster-ip-service.yaml
    - k8s/mariadb-deployment.yaml
    - k8s/server-cluster-ip-service.yaml
    - k8s/server-deployment.yaml
