apiVersion: skaffold/v2beta3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: mhdns/lions-den-server
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        - '**/*.js': .
deploy:
  kubectl:
    manifests:
      - k8s/ingress-service.yml
      - k8s/server-cluster-ip-service.yml
      - k8s/server-deployment.yml
